set -g status off

bind -n C-e next-window
bind C-x confirm-before -p "kill-session #S? (y/n)" kill-session

set-window-option -g mode-keys vi

bind-key -n C-[ copy-mode

bind-key -T copy-mode-vi C-n send-keys -X page-down
bind-key -T copy-mode-vi C-p send-keys -X page-up

unbind-key -T copy-mode-vi C-f
unbind-key -T copy-mode-vi C-b

bind-key -n C-` next-window
